//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaseExpenseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhaseExpenseDetail()
        {
            this.ActualExpenseDetails = new HashSet<ActualExpenseDetail>();
            this.EstimatedExpenseDetails = new HashSet<EstimatedExpenseDetail>();
        }
    
        public int PhaseExpenseID { get; set; }
        public Nullable<int> ExpenseHeadID { get; set; }
        public Nullable<int> ExpenseTypeID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActualExpenseDetail> ActualExpenseDetails { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimatedExpenseDetail> EstimatedExpenseDetails { get; set; }
        public virtual ExpenseDetail ExpenseDetail { get; set; }
        public virtual ExpenseHeadMaster ExpenseHeadMaster { get; set; }
        public virtual ExpenseTypeMaster ExpenseTypeMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
