//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMPEntities : DbContext
    {
        public PMPEntities()
            : base("name=PMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActualExpenseDetail> ActualExpenseDetails { get; set; }
        public virtual DbSet<AuthMapping> AuthMappings { get; set; }
        public virtual DbSet<BrandMaster> BrandMasters { get; set; }
        public virtual DbSet<ChannelMaster> ChannelMasters { get; set; }
        public virtual DbSet<ContactPersonMaster> ContactPersonMasters { get; set; }
        public virtual DbSet<CRPStatu> CRPStatus { get; set; }
        public virtual DbSet<CurrencyDetail> CurrencyDetails { get; set; }
        public virtual DbSet<CurrencySetting> CurrencySettings { get; set; }
        public virtual DbSet<CurrentStatusMaster> CurrentStatusMasters { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DNAAmbassadorDetail> DNAAmbassadorDetails { get; set; }
        public virtual DbSet<DNAManagerDetail> DNAManagerDetails { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<EstimatedExpenseDetail> EstimatedExpenseDetails { get; set; }
        public virtual DbSet<ExpenseDetail> ExpenseDetails { get; set; }
        public virtual DbSet<ExpenseHeadMaster> ExpenseHeadMasters { get; set; }
        public virtual DbSet<ExpenseTypeMaster> ExpenseTypeMasters { get; set; }
        public virtual DbSet<IndustryMaster> IndustryMasters { get; set; }
        public virtual DbSet<InitialProject> InitialProjects { get; set; }
        public virtual DbSet<InquiryTypeMaster> InquiryTypeMasters { get; set; }
        public virtual DbSet<MethodologyMaster> MethodologyMasters { get; set; }
        public virtual DbSet<OverallStatu> OverallStatus { get; set; }
        public virtual DbSet<PhaseExpenseDetail> PhaseExpenseDetails { get; set; }
        public virtual DbSet<PhaseMaster> PhaseMasters { get; set; }
        public virtual DbSet<ProductCatMaster> ProductCatMasters { get; set; }
        public virtual DbSet<ProjectAccountsDetail> ProjectAccountsDetails { get; set; }
        public virtual DbSet<ProjectClosureDetail> ProjectClosureDetails { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
        public virtual DbSet<ProjectFunding> ProjectFundings { get; set; }
        public virtual DbSet<ResearchTypeMaster> ResearchTypeMasters { get; set; }
        public virtual DbSet<SourceMaster> SourceMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<TaskAssignment> TaskAssignments { get; set; }
        public virtual DbSet<TaskPriorityMaster> TaskPriorityMasters { get; set; }
        public virtual DbSet<TaskStatusLog> TaskStatusLogs { get; set; }
        public virtual DbSet<TeamContribDetail> TeamContribDetails { get; set; }
        public virtual DbSet<TokenDetail> TokenDetails { get; set; }
        public virtual DbSet<VendorMaster> VendorMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<StatusLevelMaster> StatusLevelMasters { get; set; }
        public virtual DbSet<PageRulesMaster> PageRulesMasters { get; set; }
        public virtual DbSet<StageMaster> StageMasters { get; set; }
        public virtual DbSet<TaskMaster> TaskMasters { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
    }
}
