//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAccountsDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectAccountsDetail()
        {
            this.ProjectFundings = new HashSet<ProjectFunding>();
        }
    
        public int ProjectAccountingID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> ProjectFees { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> EstCost { get; set; }
        public Nullable<decimal> EstProfit { get; set; }
        public Nullable<decimal> ActCost { get; set; }
        public Nullable<decimal> ActProfit { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CurrencyDetail CurrencyDetail { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster1 { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFunding> ProjectFundings { get; set; }
    }
}
