//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskAssignment()
        {
            this.TaskStatusLogs = new HashSet<TaskStatusLog>();
            this.TeamContribDetails = new HashSet<TeamContribDetail>();
        }
    
        public int TaskAssignmentID { get; set; }
        public Nullable<int> TokenID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> TaskPriorityID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> LinkTask { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public Nullable<int> AssignedByID { get; set; }
        public Nullable<int> OverallStatusID { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CurrentStatusMaster CurrentStatusMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster1 { get; set; }
        public virtual EmployeeMaster EmployeeMaster2 { get; set; }
        public virtual OverallStatu OverallStatu { get; set; }
        public virtual TaskPriorityMaster TaskPriorityMaster { get; set; }
        public virtual TokenDetail TokenDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskStatusLog> TaskStatusLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamContribDetail> TeamContribDetails { get; set; }
        public virtual TaskMaster TaskMaster { get; set; }
    }
}
