//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusLog
    {
        public int TaskStatusLogID { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public Nullable<int> TaskAssignmentID { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CurrentStatusMaster CurrentStatusMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster1 { get; set; }
        public virtual TaskAssignment TaskAssignment { get; set; }
    }
}
