//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TokenDetail()
        {
            this.InitialProjects = new HashSet<InitialProject>();
            this.ProjectClosureDetails = new HashSet<ProjectClosureDetail>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
            this.TaskAssignments = new HashSet<TaskAssignment>();
        }
    
        public int TokenID { get; set; }
        public string TokenKey { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> InquiryTypeID { get; set; }
        public string Objective { get; set; }
        public string TargetAudience { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ChannelMaster ChannelMaster { get; set; }
        public virtual ContactPersonMaster ContactPersonMaster { get; set; }
        public virtual CurrentStatusMaster CurrentStatusMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster1 { get; set; }
        public virtual EmployeeMaster EmployeeMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialProject> InitialProjects { get; set; }
        public virtual InquiryTypeMaster InquiryTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectClosureDetail> ProjectClosureDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
        public virtual SourceMaster SourceMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignment> TaskAssignments { get; set; }
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
